title:    "Rioki's Corner"
url:      http://www.rioki.org
author:   Sean Farrell
email:    sean.farrell@rioki.org
markdown: kramdown
lsi:      false
pygments: true
future:   false
exclude:  [Gemfile, Gemfile.lock, wercker.yml]